Toy espresso machine powered by micro:bit and Arduino Uno

Motivation: Our 10-year-old wanted a toy espresso machine so that she could make pretend coffee for us. We built one out of cardboard, wood, and a few electronics parts that we had lying around.

Components used:

- [[https://microbit.org/new-microbit/][micro:bit v2]] ([[https://tech.microbit.org/][technical resources]])
- [[https://wiki.elecfreaks.com/en/microbit/getting-started/microbit-basic-kit/basic_kit/][ElecFreaks basic micro:bit kit]] for the panel with 5 buttons
- [[https://monkmakes.com/mb_7_seg][MonkMakes 7-segment display for micro:bit]]
- [[https://en.wikipedia.org/wiki/Arduino_Uno][Arduino Uno]]
- [[https://www.adafruit.com/product/94?srsltid=AfmBOoreMZRo-hDvyolyETdrbkOJ_gfz2r6WN0DbXO6ciIS7QO80a5DE][Adafruit Wave Shield]]
- speaker

The micro:bit is responsible for handling button input, driving the 7-segment display, and communicating with the Arduino Uno, which is responsible for playing sounds.

Sound files are too large to put on the micro:bit, and the onboard speaker is too tinny for the kinds of sounds the kiddo wanted the device to make. We used the Arduino Uno to play the WAV files because we had one lying around from a previous project and she didn't want to wait for an MP3 module.

We considered moving everything to the Arduino, but the kiddo liked her 5x5 animations. We didn't have a similar 5x5 LED display outside the micro:bit and we didn't want to go through the trouble of setting up communication from the Arduino to the micro:bit (higher voltage to lower).

* The process we eventually settled on

** micro:bit

1. Install [[https://learn.adafruit.com/micropython-basics-load-files-and-run-code/install-ampy][Ampy]] with =pipx install adafruit-ampy= so that you can more easily transfer .py files to micropython on the micro:bit.
2. Flash the [[https://github.com/bbcmicrobit/micropython/releases/tag/v1.1.1][hex file]] for micropython by mounting the micro:bit as a drive and dragging and dropping the hex file to the directory, or by using =dd=. =cp= doesn't reliably work for copying hex files to the mounted directory; the transfer times out. Instead, use a command like
   #+begin_src sh :eval no
   dd if=/path/to/your.hex of=/media/your-username/MICROBIT/image.hex bs=4k conv=fsync
   #+end_src
3. Use =ampy -p /dev/ttyACM0 put main.py= to transfer the main.py. After the transfer is complete, press the reset button on the back of the micro:bit to restart it with your program.

** Arduino and Wave Shield

1. Install the Waveshield libraries and create a sketch to play sounds. Their library includes a program to recite the first several digits of pi, it is a handy way to verify the shield works.
2. Modify the sketch to play a wav file when a button is pushed.
3. Modify the sketch to respond to signals from the micro:bit.

* Lessons learned

- Bluetooth pairing with the micro:bit was unreliable. It was better to connect via USB.
- Deployment goes faster when you automatically mount devices instead of having to click on them. In Kubuntu, you can configure that by opening the *Removable Devices* settings dialog and checking "On Attach" for all known devices or for the specific device you want.
- The ElecFreaks buttons needed to be debounced.
- The micro:bit doesn't send out a true analog signal when you use =write_analog=. Instead, it uses pulse-width modulation (PWM), which we had a hard time figuring out how to reliably read on the Arduino side. This might be also partly because of the differences between voltage levels (3.3V for the micro:bit, 5V for the Arduino). We tried using a capacitor and a resistor to get an average voltage level as an analog signal into the Arduino. We eventually settled on using pulse duration instead. 50ms differences between pulse duration was reliably detectable.
- It turns out that the micro:bit has a number of [[https://makecode.microbit.org/v0/device/pins][assignable GPIO pins]] in addition to the 3 large IO rings, so we didn't need to squeeze the Arduino connection into a single pin, and we can add other components if we want to.
- Since the communication between the micro:bit to the Arduino was one way, we didn't need a voltage level shifter to protect the micro:bit from the higher voltage used by the Arduino.
- micropython expects the entry point of the program to be named =main.py=.
- You can connect to the micro:bit via USB with =sudo screen /dev/ttyACM0 115200= (check =dmesg= to see what port to use) and see error messages or =print(..)= output instead of waiting for the error message to scroll one letter at a time. Quit with =Ctrl+a k=.
- Magnetically attaching the control panel made it easy to take off and put back on.
- It was helpful to be able to ask Claude AI to debug things or suggest what to do, especially when the kiddo was impatient and wanted snuggles.
- A power bank with two USB output ports can power both devices.

* Next steps?

- Add pictures, schematics
- Use the actual temperature as a starting point, since the micro:bit can sense the temperature of its CPU. Range: [[https://tech.microbit.org/hardware/#temperature-sensing][-40C to 105C]]
- Add some kind of magnetized group head
- The kid is going to forget to turn it off, even with an always-on LED. Might be good to have some kind of sleep mode or way to cut power, or just manually remember to check it ourselves.

* Powering the micro:bit without the USB connector

The micro:bit's USB connector sticks out too far when the toy is in play mode. Alternatives:

- **JST battery connector**: The micro:bit v2 has a JST connector designed for a 3.7V LiPo battery. Feeding 5V into it may damage the board (too high); feeding 3.3V regulated power into it may not work reliably because the onboard regulator needs headroom above 3.3V to function.
- **Edge connector 3V and GND pins**: The micro:bit edge connector exposes a 3V pin and GND that accept regulated 3.3V directly, bypassing the onboard regulator. A JST connector with 20cm cable wired to these pins works cleanly with a DC-DC buck converter such as the AMS1117 3.3V (4.75V–12V input, 3.3V/800mA output). See [[https://tech.microbit.org/hardware/edgeconnector/][micro:bit edge connector pinout]].
- **90-degree USB adapter**: If the cable clearance is the only issue, a 90-degree USB adapter may solve it without any additional hardware.

The edge connector route is the cleanest: power the buck converter from the same 5V USB power bank, and run 3.3V from the buck converter to the edge connector 3V and GND pins via a 2-pin JST connector.

* Schematics (planned DFPlayer Mini upgrade)

** Power Rails

#+begin_example
  +------------------+
  |  USB Power Bank  |
  |       5V         |
  +--------+---------+
           |
           +------------ 5V rail --------+-------------------+
           |                             |                   |
     +-----+----------+           +------+------+  +---------+-------+
     | Mini DC-DC     |           | Level       |  | DFPlayer Mini   |
     | Buck Converter |           | Shifter     |  | VCC         GND +--+
     | IN=5V  OUT=3.3V|           | HV = 5V     |  +-----------------+  |
     +-----+----------+           +------+------+                       |
           |                             |                              |
           +------------ 3.3V rail ------+ LV = 3.3V                   |
           |                             |                              |
     +-----+-------+              +------+------+                      |
     | micro:bit   |              | Level       |                      |
     | 3V pin      |              | Shifter     |                      |
     | (via JST to |              | LV = 3.3V   |                      |
     |  edge conn) |              +-------------+                      |
     +-------------+                                                   |
           |                                                           |
           +--- 3V also powers ElecFreaks panel and 7-seg (edge conn) |
                                                                       |
  GND (common to all devices) <-----------------------------------------+

  Note: buck converter module has decoupling caps integrated on PCB.
  Set output voltage jumpers [A] and [B] on buck converter for 3.3V.
#+end_example

** Signal Connections

#+begin_example
                  +--------------------------+
  ElecFreaks      |       micro:bit v2       |      MonkMakes
  5-button panel  |                          |      7-segment display
  (resistor       |                          |      (UART, 3.3V)
   ladder)        |                          |
                  |                          |
  button out ---> pin1 (ADC)                 |
  VCC <--------- 3V                          |
  GND <--------- GND   pin2 (UART TX) ------+-----------> RX
                  |                          |
                  |    pin0 (UART TX) -------+---> Level Shifter --> DFPlayer RX
                  |                          |     LV ch1 (3.3V)    HV ch1 (5V)
                  +--------------------------+

  DFPlayer Mini outputs:
    SPK+ ----> Speaker +
    SPK- ----> Speaker -

  Note: The 5 buttons share a single ADC pin via a resistor ladder.
  Each button produces a distinct voltage (A~0V, B~0.25V, C~0.40V,
  D~0.50V, E~1.9V, none~3.3V) read by pin1 on the micro:bit.
#+end_example

* Resources

- [[https://tech.microbit.org/hardware/edgeconnector/][micro:bit edge connector pinout]]
- [[https://tech.microbit.org/hardware/powersupply/][micro:bit power supply reference]]

* Questions? Improvements?

[[mailto:sacha@sachachua.com][sacha@sachachua.com]]
